# GitHub Sponsors funding options
github: [rahmaniyaShekh]

# Patreon
# patreon: your_patreon_username

# Open Collective
# open_collective: your_opencollective_name

# Ko-fi
# ko_fi: your_kofi_username

# Buy Me a Coffee
# custom: https://www.buymeacoffee.com/your_username

# PayPal
# custom: https://paypal.me/your_paypal_username